apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-certificate
spec:
  dnsNames:
    - argocd.naythanc.dev
  secretName: jc-dev-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer