apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jc-dev

bases:
  - ../../base
  - issuer-cloudflare.yml
  - auth-service-ingress.yml
  # - postgres-sealed.yml

# patches:
# - target:
#     kind: Deployment
#   path: container_resources_patch.yml

configMapGenerator:
  - name: error-pages
    files:
      - 401.html
      - 503.html
    options:
      disableNameSuffixHash: true
