apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jc-dev

bases:
  - ../../base
  - postgres-sealed.yml

images:
- name: registry.naythanc.dev/yet-another-hello-world
  newName: registry.naythanc.dev/yet-another-hello-world
  newTag: dev