apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jc-dev

bases:
  - ../../base
  # - postgres-sealed.yml

# patches:
# - target:
#     kind: Deployment
#   path: container_resources_patch.yml

configMapGenerator:
  - name: error-pages
    files:
      - 503.html
    options:
      disableNameSuffixHash: true

images:
- name: registry.naythanc.dev/yet-another-hello-world
  newName: registry.naythanc.dev/yet-another-hello-world
  newTag: dev