apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jc-dev

bases:
  - ../../base
  - postgres-sealed.yml

images:
- name: docker-registry.docker-registry.svc:5000/yet-another-hello-world
  newName: docker-registry.docker-registry.svc:5000/yet-another-hello-world
  newTag: dev