apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAeDlY5WBEv0ftQ8kkMRmILmuGLM8F5FmZJAhha5HrBmYJTiVR9eqE7zG20xgxMHMjvN9ETO/sOn/F8FwC7Q6onCmYc3evniIBEPDlzn34y30jnmQA4UFiJfl36tczInS4EUvi8RcC+hy+B+//RQ+Syl8vVZud6SF0r8uoie5xzlLeDUGz9u4pwIz7BizB2gPhBGbEPfzJ1qCY4NpfvQcpAGifsBM+jJalKlJbX+pPNAaP24wnU5j2g1ZAuddPlmVhyr9mj0m4DCcceb4Gfo9f5nrmwovFwSV87RT6ts54ye5uL99RL4opTQtNUVGmBd+5rLFqZL2KV/QeNkgwBLsDU3GPdm36efy8EwfhYK4SQFPct8gtk1c63MxXllg+fjK4Y/wYaXhzY9/4NGlyjjH4aVPFrJkJfooiWg2jKdZIsr3ggPhf4VAhWdtWyVdpEbnC6EJSF62ssLVwHZQzvaTSSau3/KJI/sqMCOWMo07aE7SmiO9NIur2/3+S7U99sOH7jL1UEh/BZRSXUDzt+9uvBlYoj1BzjRg4Be0CVap2KbxCSetpPWLPYh6g80dUzk+09SDLjBVNl2oftDJr98xl6YApPfKd+a3LhBCzm0l+xNT9EMJPdraIo6ycivRjVwAe9s0FXXxoEADunZezL7RSPDwq8tMJbzXlFffqgiPGlvf4NUZRJ6aQCNDLuxpaO8cNgm3opvMifbmUyDw==
    POSTGRES_USER: AgAqBBNkPVpubD36bW1FupsjnkK79yOObVRUiBZ56YMZiWomPGG97z2mye4NvfFkHgYhNWJzAUyHRp1fv94UaYZelWABBJHZEleEBpk7BxLvROiGNu25N6Z7Iq8EHrdsqLKFbRdhEUX5vp6XgOHgNS/fzoj5eM2Jauq+3lCrKzuz5/lMOT6qCUd+gUFEH1/xegCpNFbbWgvKHbGhTC6xGTeH7SU45ookoXwqPL69LXx5076eEGvLTuRAt/baxOS+SD2JF980X1DqkUT3hsfIYKHRvSSfHK9bQXM/lMNEv9vBiVeoE6VuJsuFrkK5CSFwcnc50mSuPdhe8ZLxIjnLs7DksaUhGp5myjg1VxIXuNNsZi/xLNWstdkcGttL6ZlxVp2sXlvjE/EDQSngN2unicohLgDxwTPeasCTM62VfP8s34GjUloVwLje/oyJiaCrA/krflfRX4YUL1b/iobC5oNeSgN5pONtJC2t1tekxMAjhHkzAGwQrNhfW9k6DhFIvuIh24xcVQYMXHikv+N54PmnFFR1Nl7rDEwhIOHxjBD8KWUXXh4zAoCwNcyrDjwwVtqj0kuoaiRvf6DK3M7OzN+rDk5RkjXg7SuVDD38KaDZ8dGxKpf/OUO7oFNRfQyZQcyAw7ensnc2rIDBoHGtdrCt1tq29Se81u+1EzGg0lPTeqREqqhSGnArlv5pGTsjW3CFNeo9LN6Zfg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: jc-dev

