apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-certificate
  namespace: longhorn-system
spec:
  dnsNames:
  - longhorn.naythanc.dev
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - longhorn.naythanc.dev
  secretName: longhorn-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer