apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
commonLabels:
  app: longhorn
resources:
  - longhorn-cert.yml
  - longhorn-ingress.yml
  - sealed-longhorn-auth.yml