apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-certificate
spec:
  dnsNames:
  - longhorn.naythanc.dev
  secretName: longhorn-tls
  issuerRef:
    name: cloudflare-issuer
    kind: Issuer