apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-certificate
spec:
  dnsNames:
  - to-be-replaced
  secretName: registry-tls
  issuerRef:
    name: cloudflare-issuer
    kind: Issuer