apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-certificate
spec:
  dnsNames:
  - test.url
  secretName: registry-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer