apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: person-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  - port: 9090
    protocol: TCP
    targetPort: 9090
    name: actuator
  type: ClusterIP