apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: person-service
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: person-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: POSTGRES.URL
          value: postgres-svc.postgres.svc
        - name: DB.USERNAME
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USER
              name: postgres-secret
        - name: DB.PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: postgres-secret
        image: registry.naythanc.dev/person-service:dev
        name: person-service
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          - name: actuator
            containerPort: 9090
            protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/liveness
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 30
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/readiness
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 30
        startupProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/liveness
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 30
        resources: {}
      restartPolicy: Always
status: {}