apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webapp
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: simple-webapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: registry.naythanc.dev/simple-webapp:latest
        imagePullPolicy: Always
        name: simple-webapp
        ports:
          - name: http
            containerPort: 3000
            protocol: TCP
        resources: {}
      securityContext: {}
      terminationGracePeriodSeconds: 30
      restartPolicy: Always