apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-webapp
  name: simple-webapp-svc
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: simple-webapp
  type: ClusterIP
status:
  loadBalancer: {}