apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-webapp
  name: simple-webapp
  namespace: jc-dev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: simple-webapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simple-webapp
    spec:
      containers:
      - image: registry.naythanc.dev/simple-webapp:dev
        imagePullPolicy: Always
        name: simple-webapp
        resources: {}
      securityContext: {}
      terminationGracePeriodSeconds: 30