apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-errors
  labels:
    app.kubernetes.io/name: nginx-errors
    app.kubernetes.io/part-of: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-errors
      app.kubernetes.io/part-of: ingress-nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-errors
        app.kubernetes.io/part-of: ingress-nginx
    spec:
      containers:
      - name: nginx-error-server
        image: quay.io/naythanc/nginx-errors:v1.0-arm64
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8443
          name: https
        # Setting the environment variable DEBUG we can see the headers sent 
        # by the ingress controller to the backend in the client response.
        # env:
        # - name: DEBUG
        #   value: "true"

        # Mounting custom error page from configMap
        volumeMounts:
        - name: error-pages
          mountPath: /www

      # Mounting custom error page from configMap
      volumes:
      - name: error-pages
        configMap:
          name: error-pages
          items:
          - key: "401.html"
            path: "401.html"
          - key: "503.html"
            path: "503.html"