apiVersion: v1
kind: Service
metadata:
  name: nginx-errors
  labels:
    app: ingress-nginx-errors
spec:
  selector:
    app: ingress-nginx-errors
  ports:
    - port: 80
      targetPort: 8080
      name: http
    - port: 443
      targetPort: 8443
      name: https