apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-certificate
  namespace: docker-registry
spec:
  dnsNames:
  - registry.naythanc.dev
  secretName: registry-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer