apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesJson6902:
- target:
    version: v1
    kind: Deployment
    name: docker-registry
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: "registry:2"
- target:
    version: v1
    kind: Certificate
    name: letsencrypt-certificate
  patch: |-
    - op: replace
      path: /spec/dnsNames/0
      value: "registry.naythanc.dev"
- target:
    version: v1
    kind: Ingress
    name: docker-registry
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: "registry.naythanc.dev"
    - op: replace
      path: /spec/rules/0/host
      value: "registry.naythanc.dev"