apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: postgres-db

resources:
  - postgresql-pvc.yml
  - postgres-db.yml
  - postgres-svc.yml

patchesStrategicMerge:
- add_env.yml
- add_volume.yml