apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-db
  name: postgres-svc
spec:
  ports:
  - name: postgres-port
    port: 5432
    targetPort: 5432
    protocol: TCP
    nodePort: 30001
  selector:
    app: postgres-db
  type: NodePort