apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-certificate
spec:
  dnsNames:
    - naythanc.dev
  secretName: jc-dev-tls
  issuerRef:
    name: cloudflare-issuer
    kind: Issuer