apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-certificate
  namespace: jc-dev
spec:
  dnsNames:
    - naythanc.dev
  secretName: jc-dev-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer