apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  template:
    metadata:
    spec:
      containers:
      - image: registry.naythanc.dev/yet-another-hello-world
        name: hello-world
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/liveness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        ports:
          - containerPort: 8080
            protocol: TCP
            name: server-port
        resources: {}
      restartPolicy: Always